version: '3'
services:
  nginx:
    image: nginx:1.19.9-alpine
    restart: always
    links:
      - app:app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Nginxの設定ファイルを上書きする
      - /home/ec2-user/build/nginx/conf/mesimasi.com.conf:/etc/nginx/conf.d/mesimasi.com.conf:ro
      - /home/ec2-user/build/nginx/conf/key.pem:/etc/ssl/private/key.pem:ro
      - /home/ec2-user/build/nginx/conf/cert.pem:/etc/ssl/certs/cert.pem:ro
      - /home/ec2-user/build/nginx/conf/dhparam.pem:/etc/nginx/ssl/dhparam.pem
    networks:
      - blog-network

  db:
    image: mysql:8.0
    command: mysqld
    volumes:
      # MySQLの設定ファイル
      - /home/ec2-user/build/db/my.cnf:/etc/mysql/conf.d/my.cnf
      # DBのデータを永続化する
      - db-data:/var/lib/mysql
    networks:
      - blog-network

  app:
    build:
      context: .
      dockerfile: ./build/app/Dockerfile
    command: /blog-server
    depends_on:
      - db
    environment:
      - GIN_MODE=release
      - TZ=Asia/Tokyo
      - MIGRATION_FILE=/migrations
      - DB_HOST=db
      - ENV=prod
      - AUTH_KEY
      - AWS_ACCESS_KEY
      - AWS_REGION
      - AWS_S3_BUCKET_NAME
      - AWS_SECRET_KEY
      - ECR_DOMAIN
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - ENV
    entrypoint:
      - dockerize
      - -timeout
      - 60s
      - -wait
      - tcp://db:3306
    networks:
      - blog-network

volumes:
  db-data:

networks:
  blog-network:
    driver: bridge
    external: true