name: Test
on: push

jobs:
  lint:
    name: Lint codes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          args: --enable=golint,gosec,prealloc,gocognit,bodyclose,gofmt

  goone:
    name: Check whether if n+1 problems exists
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install goone
        run: go get -u github.com/masibw/goone/cmd/goone
      - name: run goone
        run: go vet -vettool=`which goone` ./...