name: Test
on: Push

jobs:
  test:
    name: Test local sources
    strategy:
      fall-fast: false
      max-parallel: 3
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.15.6
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.6
      - name: Restore cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys:  ${{ runner.os }}-go-
      - name: Get dependencies
        run: go mod download
      - name: Test
        run: go test ./...